# Generated by Django 4.1.2 on 2022-12-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0003_studentss'),
    ]

    operations = [
        migrations.CreateModel(
            name='regdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='studentss',
        ),
    ]
