# Generated by Django 4.1.2 on 2023-01-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0003_newdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newdb',
        ),
    ]
